"""
PACE Plan Injector — Working-Hook Pair to _14
==============================================
Hook: message_loop_prompts_after
Priority: _23 (after _22_reasoning_state_injector, before _55_memory_relevance_filter)

This is the consumer side of the PACE plan pair.

  Generator side (turn N, before_main_llm_call):
    _14_pace_plan_generator — generates the PACE plan via LLM call,
                              writes to agent._pace_plan. Survives turn boundaries
                              (locked after creation unless _pace_advance_tier).

  THIS FILE (turn N, message_loop_prompts_after):
    Reads agent._pace_plan and injects into loop_data.history_output[-1].
    Lightweight: no LLM calls (this hook is inside prepare_prompt where LLM
    calls aren't permitted).

Why this exists: _14's injection in before_main_llm_call is discarded because
prepare_prompt() has already assembled the prompt by the time that hook fires.
Without this consumer, the model never sees its PACE plan and can't reason about
which tier to execute when the primary approach fails. See state/wiring/
exocortex_wiring_and_logic.html §09 for the full chain diagram.

Reads:
  - agent._pace_plan (generated by _14)
Writes:
  - loop_data.history_output[-1]["content"] (prepend PACE plan block)
Log tag: [PACE-INJ-23]
"""

from typing import Any, Optional

from agent import Agent, LoopData
from helpers.extension import Extension

PACE_PLAN_KEY = "_pace_plan"
TIERS = ["primary", "alternate", "contingency", "emergency"]


class PacePlanInjector(Extension):
    """message_loop_prompts_after: inject PACE plan into the user message."""

    async def execute(self, loop_data: LoopData = LoopData(), **kwargs) -> Any:
        try:
            # Subordinate context — skip per DEC-028
            if self.agent.get_data(Agent.DATA_NAME_SUPERIOR) is not None:
                return

            plan = getattr(self.agent, PACE_PLAN_KEY, None)
            if not plan or not isinstance(plan, dict):
                return

            # Sanity: plan must have steps to be meaningful
            steps = plan.get("steps", [])
            if not steps:
                return

            block = _build_injection_block(plan)
            if not block:
                return

            user_msg = _get_last_user_message(loop_data.history_output)
            if not user_msg:
                return

            existing = user_msg.get("content", "")
            user_msg["content"] = block + "\n\n" + str(existing)

            print(
                f"[PACE-INJ-23] step={plan.get('current_step', '?')}/{len(steps)} "
                f"tier={plan.get('active_tier', '?')} "
                f"escalations={plan.get('tier_escalations', 0)}",
                flush=True,
            )
        except Exception as e:
            # Graceful degradation
            try:
                self.agent.context.log.log(
                    type="warning",
                    content=f"[PACE-INJ-23] error (passthrough): {e}",
                )
            except Exception:
                pass


# ── Inline helpers (no cross-extension imports) ───────────────────────────────

def _build_injection_block(plan: dict) -> str:
    """Build the compressed [PACE PLAN] read-only context block.

    Compression decision (Kestrel 2026-05-17, predeployment investigation):
    the model only needs the *current move* — the active tier's action on the
    current step. The full multi-step / four-tier plan was ~530 fixed tokens
    per turn with ~11 of 12 tier-lines irrelevant on any given turn. The full
    plan still lives on agent._pace_plan for the Supervisor (get_plan_context /
    get_current_step_action read it directly); only the model's view is trimmed.

    _14_pace_plan_generator._build_injection_block is intentionally NOT changed
    — that injection is discarded in before_main_llm_call anyway (seam #7), and
    the Supervisor reads the raw dict, not the rendered block. This trim is
    scoped to the working-hook consumer only.

    Compressed block ≈ ~180 tokens (was ~530).
    """
    current_step = plan.get("current_step", 1)
    active_tier  = plan.get("active_tier", "primary")
    steps        = plan.get("steps", [])
    total        = len(steps)
    escalations  = plan.get("tier_escalations", 0)
    esc_note     = f" | Escalations: {escalations}" if escalations > 0 else ""

    lines = [
        "[PACE PLAN — ACTIVE]",
        f"Task: {plan.get('task_summary', '')[:140]}",
        f"Domain: {plan.get('domain', '?')} | Step: {current_step}/{total} | "
        f"Active Tier: {active_tier.upper()}{esc_note}",
        "",
    ]

    # Find the current step only
    cur = next((s for s in steps if s.get("step", 0) == current_step), None)
    if cur is None:
        # Out-of-range / completed plan — emit header + a safe note rather than nothing
        lines.append("(No active step — plan complete or step index out of range.)")
    else:
        name   = cur.get("name", "")
        action = cur.get(active_tier, "")
        lines.append(f"Step {current_step}/{total} — {name} ◄ CURRENT")
        lines.append(f"  {active_tier.upper()}: {action}  ← EXECUTE THIS")
        # Escalation path = tiers strictly after the current active tier
        idx = TIERS.index(active_tier) if active_tier in TIERS else 0
        remaining = TIERS[idx + 1:]
        if remaining:
            lines.append(
                "  (If blocked, escalate via _pace_advance_tier: "
                + " → ".join(remaining) + ".)"
            )
        else:
            lines.append(
                "  (Emergency tier — preserve partial work, acknowledge the gap, do not fabricate.)"
            )
    lines.append("")

    lines += [
        "RULES:",
        "• If blocked at current tier, set _pace_advance_tier and execute the next tier on this same step.",
        "• Emergency is always available — acknowledge failure and preserve partial work. Never fabricate.",
        "• Do not skip to a new step until the current step's active tier has been attempted.",
        "[/PACE PLAN]",
    ]

    return "\n".join(lines)


def _get_last_user_message(history_output: list) -> Optional[dict]:
    """Find the most recent user message in the assembled history_output."""
    if not history_output:
        return None
    for msg in reversed(history_output):
        if not isinstance(msg, dict):
            continue
        if not msg.get("ai", True):
            return msg
    return None
